language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy

install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - pip install zetup[commands]
  - zetup install
  - pip install -U pytest pytest-cov
  - pip install -U tox tox-travis

script:
  # - zetup pytest
  - python -m pytest -vv --doctest-modules moretools test --cov moretools --cov-report term-missing
  - zetup tox
