sudo: false
git:
  depth: false

language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy

install:
  - pip install -U pip setuptools
  - pip install -U -e .
  - pip install -U -r test-requirements.txt
  - pip install -U tox tox-travis

script:
  - pytest -vv --doctest-modules moretools test --cov moretools --cov-report term-missing
  - tox -r -v

  - pip uninstall moretools
  - pip install zetup[all]
  - zetup install
  # - zetup pytest
  - zetup tox
